version: '3.8'

name: mspw-db

services:
  db:
    container_name: db
    build: .
    restart: always
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: mspwTest
      MYSQL_USER: mspwUser
      MYSQL_PASSWORD: wcy19il1s0
    volumes:
      - db_data:/var/lib/mysql
      - ./populate.sql:/data/import.sql
#      - ./import-database.sh:/docker-entrypoint-initdb.d/import-database.sh
    ports:
      - 3306:3306

  adminer:
    depends_on:
      - db
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
