version: '3.8'

name: mspw-db

services:
  db:
    container_name: db
    restart: always
    image: mysql:latest
    build: .
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: mspwTest
      MYSQL_USER: mspwUser
      MYSQL_PASSWORD: wcy19il1s0
    volumes:
      - db_data:/var/lib/mysql
      - ./populate.sql:/data/import.sql
    ports:
      - "3306:3306"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
