package pl.edu.wat.mspw_backend.service;

import pl.edu.wat.mspw_backend.model.SprzetWojEntity;
import pl.edu.wat.mspw_frontend.model.SprzetWojDto;

public class SprzetWojService extends GenericService<SprzetWojEntity, SprzetWojDto> {
    public SprzetWojService() {
        super(SprzetWojEntity.class,
                e -> new SprzetWojDto(e.getId(),
                        e.getNazwa(),
                        e.getSkrot(),
                        e.getKod(),
                        e.getKategoriaFk(),
                        e.getKlasa(),
                        e.getObsluga(),
                        e.getOpancerzony(),
                        e.getKosztJednCykluZycia(),
                        e.getKosztJednNabycia(),
                        e.getKosztJednUtrzymWyszkPerson(),
                        e.getMasa(),
                        e.getDlug(),
                        e.getSzerok(),
                        e.getWysok(),
                        e.getPotencjalBoj(),
                        e.getValue(),
                        e.getPojemZbiorPaliwa(),
                        e.getPojemZbiorPaliwaDodat(),
                        e.getPojemAkumulatorow(),
                        e.getJezdzacy(),
                        e.getLatajacy(),
                        e.getPlywajacy(),
                        e.getPrzenosny(),
                        e.getCiagniony(),
                        e.getEfektorLacznFk(),
                        e.getRodzajSrodowFk(),
                        e.getEfektorJezdnyFk(),
                        e.getEfektorPlywaniaFk(),
                        e.getEfektorInzFk(),
                        e.getEfektorWeFk(),
                        e.getParamKadlubaFk(),
                        e.getEfektorTranspFk(),
                        e.getEfektorLataniaFk(),
                        e.getEfektorRozpozFk(),
                        e.getKlasaPrzyrzOc(),
                        e.getMoc(),
                        e.getZuzyciePaliwaPraca()),
                d -> new SprzetWojEntity(d.getId(),
                        d.getNazwa(),
                        d.getSkrot(),
                        d.getKod(),
                        d.getKategoriaFk(),
                        d.getKlasa(),
                        d.getObsluga(),
                        d.getOpancerzony(),
                        d.getKosztJednCykluZycia(),
                        d.getKosztJednNabycia(),
                        d.getKosztJednUtrzymWyszkPerson(),
                        d.getMasa(),
                        d.getDlug(),
                        d.getSzerok(),
                        d.getWysok(),
                        d.getPotencjalBoj(),
                        d.getValue(),
                        d.getPojemZbiorPaliwa(),
                        d.getPojemZbiorPaliwaDodat(),
                        d.getPojemAkumulatorow(),
                        d.getJezdzacy(),
                        d.getLatajacy(),
                        d.getPlywajacy(),
                        d.getPrzenosny(),
                        d.getCiagniony(),
                        d.getEfektorLacznFk(),
                        d.getRodzajSrodowFk(),
                        d.getEfektorJezdnyFk(),
                        d.getEfektorPlywaniaFk(),
                        d.getEfektorInzFk(),
                        d.getEfektorWeFk(),
                        d.getParamKadlubaFk(),
                        d.getEfektorTranspFk(),
                        d.getEfektorLataniaFk(),
                        d.getEfektorRozpozFk(),
                        d.getKlasaPrzyrzOc(),
                        d.getMoc(),
                        d.getZuzyciePaliwaPraca())
        );
    }
}